language: python
dist: xenial

services:
 - xvfb

addons:
  apt:
    packages:
      - herbstluftwm
      - libxkbcommon-x11-0

jobs:
  allow_failures:
    - name: "New Tag Compat"
    - name: "Python 3.7 Compat"
    - name: "Python 3.8 Compat"

  include:
    - stage: "Init"
      name: "Create Base Env from YAML"
      workspaces:
        create:
          name: conda_base
          paths:
            - miniconda
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p miniconda
        - source "miniconda/etc/profile.d/conda.sh"
        - conda activate
        - hash -r
        # Use our condarc
        - cp condarc ~/.condarc
        - conda config --set always_yes yes --set changeps1 no
        - conda install conda-build anaconda-client packaging
        # Reboot conda after updating conda to avoid subtle path bugs
        - conda deactivate
        - conda activate
        # Useful for debugging any issues with conda
        - conda info -a
      script:
        # Always create the environment from yaml
        - conda env create -q -n pcds-test -f envs/pcds/env.yaml

    - stage: "Build"
      name: "Setup Tests (Tag)"
      workspaces:
        use: conda_base
        create:
          name: test_tag
          paths:
            - test_repos
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate pcds-test
        - mkdir test_repos
        - cd test_repos
      script:
        - python ../scripts/test_setup.py pcds --tag
        - readlink -f */run_tests.py

    - stage: "Build"
      name: "Setup Tests (Dev)"
      workspaces:
        use: conda_base
        create:
          name: test_dev
          paths:
            - test_repos
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate pcds-test
        - mkdir test_repos
        - cd test_repos
      script:
        - python ../scripts/test_setup.py pcds
        - readlink -f */run_tests.py

    - stage: "Test"
      name: "Python 3.6 Unit Tests"
      workspaces:
        use:
        - conda_base
        - test_tag
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate pcds-test
        - cd test_repos
      before_script:
        # Run windows manager
        - "herbstluftwm &"
        - sleep 1
      script:
        - ../scripts/run_all_tests.sh pcds

    - stage: "Test"
      name: "New Tag Compat"
      workspaces:
        use: conda_base
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate pcds-test
      script:
        - cd scripts
        - python update_tags.py pcds
        - ./update_env.sh pcds-test pcds

    - stage: "Test"
      name: "Python 3.7 Compat"
      workspaces:
        use: conda_base
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate pcds-test
      script:
        - conda install python=3.7

    - stage: "Test"
      name: "Python 3.8 Compat"
      workspaces:
        use: conda_base
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate pcds-test
      script:
        - conda install python=3.8
