language: python
dist: xenial

services:
 - xvfb

addons:
  apt:
    packages:
      - herbstluftwm
      - libxkbcommon-x11-0

jobs:
  fast_finish: true

  allow_failures:
    - name: "Clone Tests (Dev)"
    - name: "Python 3.6 Next Env"
    - name: "Python 3.7 Next Env"
    - name: "Python 3.8 Next Env"
    - name: "Python 3.6 Next Env Unit Tests"
    - name: "Python 3.6 Master Branch Unit Tests"
    - name: "Python 3.7 Next Env Unit Tests"
    - name: "Python 3.8 Next Env Unit Tests"

  include:
    - stage: "Load Env"
      name: "Create Base Env from YAML"
      workspaces:
        create:
          name: conda_base
          paths:
            - miniconda
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p miniconda
        - source "miniconda/etc/profile.d/conda.sh"
        - conda activate
        - hash -r
        # Use our condarc
        - cp condarc miniconda/.condarc
        - conda config --set always_yes yes --set changeps1 no
        - conda install conda-build anaconda-client packaging
        # Reboot conda after updating conda to avoid subtle path bugs
        - conda deactivate
        - conda activate
        # Useful for debugging any issues with conda
        - conda info -a
        - which python
      script:
        # Always create the environment from yaml
        - conda env create -q -n pcds-test -f envs/pcds/env.yaml

    - stage: "Clone Tests"
      name: "Clone Tests (Tag)"
      workspaces:
        use: conda_base
        create:
          name: test_tag
          paths:
            - test_repos
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate pcds-test
        - mkdir test_repos
        - cd test_repos
        - conda info -a
        - which python
      script:
        - python ../scripts/test_setup.py pcds --tag
        - readlink -f */run_tests.py
        - cd ..

    - stage: "Clone Tests"
      name: "Clone Tests (Dev)"
      workspaces:
        use: conda_base
        create:
          name: test_dev
          paths:
            - test_repos
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate pcds-test
        - mkdir test_repos
        - cd test_repos
        - conda info -a
        - which python
      script:
        - python ../scripts/test_setup.py pcds
        - readlink -f */run_tests.py
        - cd ..

    - stage: "Main Test"
      name: "Current Env Unit Tests"
      workspaces:
        use:
        - conda_base
        - test_tag
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate pcds-test
        - cd test_repos
        - conda info -a
        - which python
      before_script:
        # Run windows manager
        - "herbstluftwm &"
        - sleep 1
      script:
        - ../scripts/run_all_tests.sh pcds

    - stage: "Extra Builds"
      name: "Python 3.6 Next Env"
      workspaces:
        use: conda_base
        create:
          name: py36
          paths:
            - miniconda
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate
        - python scripts/update_tags.py pcds --debug
        - conda activate pcds-test
        - conda info -a
        - which python
      script:
        - pushd scripts
        - timeout 10m ./update_env.sh pcds-test pcds
        - popd
      after_failure:
        # Nuke the miniconda to skip workspace creation
        - rm -rf miniconda

    - stage: "Extra Builds"
      name: "Python 3.7 Next Env"
      workspaces:
        use: conda_base
        create:
          name: py37
          paths:
            - miniconda
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate
        - python scripts/update_tags.py pcds --debug
        - conda activate pcds-test
        - conda info -a
        - which python
      script:
        - timeout 5m conda install python=3.7
        - pushd scripts
        - timeout 10m ./update_env.sh pcds-test pcds
        - popd
      after_failure:
        # Nuke the miniconda to skip workspace creation
        - rm -rf miniconda

    - stage: "Extra Builds"
      name: "Python 3.8 Next Env"
      workspaces:
        use: conda_base
        create:
          name: py38
          paths:
            - miniconda
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate
        - python scripts/update_tags.py pcds --debug
        - conda activate pcds-test
        - conda info -a
        - which python
      script:
        - timeout 5m conda install python=3.8
        - pushd scripts
        - timeout 10m ./update_env.sh pcds-test pcds
        - popd
      after_failure:
        # Nuke the miniconda to skip workspace creation
        - rm -rf miniconda

    - stage: "Extra Tests"
      name: "Python 3.6 Next Env Unit Tests"
      workspaces:
        use:
        - py36
        - test_tag
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate pcds-test
        - cd test_repos
        - conda info -a
        - which python
      before_script:
        # Run windows manager
        - "herbstluftwm &"
        - sleep 1
      script:
        - ../scripts/run_all_tests.sh pcds

    - stage: "Extra Tests"
      name: "Python 3.6 Master Branch Unit Tests"
      workspaces:
        use:
        - py36
        - test_dev
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate pcds-test
        - cd test_repos
        - |
          for repo in *
          do
            export PYTHONPATH="$PYTHONPATH:$(readlink -f $repo)"
          done
        - conda info -a
        - which python
      before_script:
        # Run windows manager
        - "herbstluftwm &"
        - sleep 1
      script:
        - ../scripts/run_all_tests.sh pcds

    - stage: "Extra Tests"
      name: "Python 3.7 Next Env Unit Tests"
      workspaces:
        use:
        - py37
        - test_tag
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate pcds-test
        - cd test_repos
        - conda info -a
        - which python
      before_script:
        # Run windows manager
        - "herbstluftwm &"
        - sleep 1
      script:
        - ../scripts/run_all_tests.sh pcds

    - stage: "Extra Tests"
      name: "Python 3.8 Next Env Unit Tests"
      workspaces:
        use:
        - py38
        - test_tag
      install:
        - source miniconda/etc/profile.d/conda.sh
        - conda activate pcds-test
        - cd test_repos
        - conda info -a
        - which python
      before_script:
        # Run windows manager
        - "herbstluftwm &"
        - sleep 1
      script:
        - ../scripts/run_all_tests.sh pcds
