language: python
sudo: false

matrix:
  include:
    - python: 3.6

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda activate
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client
  - conda update -q conda conda-build
  # Useful for debugging any issues with conda
  - conda info -a
  # Mutate the env to skip file channels and daq packages
  - egrep -v "file:|pydaq" pcds.yaml > test.yaml
  # Set up the environment
  - conda env create -q -n test-environment -f test.yaml
  - conda activate test-environment
  # Check out the tests for all of our packages
  - python test_setup.py test.yaml
  # Show us which test scripts exist
  - readlink -f */run_tests.py

script:
  # - python run_tests.py */tests */*/tests
  - |
    for dir in *
    do
      if [ -f "${dir}/run_tests.py" ]; then
        pushd "${dir}"
        python run_tests.py
        popd
      fi
    done
