language: python
dist: xenial

services:
 - xvfb

addons:
  apt:
    packages:
      - herbstluftwm
      - libxkbcommon-x11-0

jobs:
  fast_finish: true

  allow_failures:
    - name: "Python 3.9 Master Branch Unit Tests"
    - name: "Python 3.10 Next Env Unit Tests"

  include:
    - name: "Current Env Unit Tests"
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p miniconda
        - source miniconda/etc/profile.d/conda.sh
        - conda activate
        - hash -r
        # Use our condarc
        - cp condarc miniconda/.condarc
        - conda config --set always_yes yes --set changeps1 no
        - conda install conda-build anaconda-client packaging mamba
        # Reboot conda after updating conda to avoid subtle path bugs
        - conda deactivate
        - conda activate
        # Useful for debugging any issues with conda
        - conda info -a
        - which python
        # Always create the environment from yaml
        - mamba env create -q -n pcds-test -f envs/pcds/env.yaml
        - conda activate pcds-test
        - conda list
        # Set up the tests
        - cd scripts
        - python test_setup.py pcds --tag
      before_script:
        # Run windows manager
        - "herbstluftwm &"
        - sleep 1
      script:
        - ./run_all_tests.sh pcds

    - name: "Python 3.9 Master Branch Unit Tests"
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p miniconda
        - source miniconda/etc/profile.d/conda.sh
        - conda activate
        - hash -r
        # Use our condarc
        - cp condarc miniconda/.condarc
        - conda config --set always_yes yes --set changeps1 no
        - conda install conda-build anaconda-client packaging mamba
        # Reboot conda after updating conda to avoid subtle path bugs
        - conda deactivate
        - conda activate
        - conda config --add channels pcds-dev
        # Useful for debugging any issues with conda
        - conda info -a
        - which python
        - cd scripts
        - python update_tags.py pcds
        - travis_wait 21 timeout 20m ./create_base_env.sh dev-3.9 pcds 3.9
        - conda activate pcds-dev-3.9
        - conda list
        # Set up the tests
        - python test_setup.py pcds
        - |
          for repo in *
          do
            export PYTHONPATH="$PYTHONPATH:$(readlink -f $repo)"
          done
      before_script:
        # Run windows manager
        - "herbstluftwm &"
        - sleep 1
      script:
        - ./run_all_tests.sh pcds

    - name: "Python 3.9 Next Env Unit Tests"
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p miniconda
        - source miniconda/etc/profile.d/conda.sh
        - conda activate
        - hash -r
        # Use our condarc
        - cp condarc miniconda/.condarc
        - conda config --set always_yes yes --set changeps1 no
        - conda install conda-build anaconda-client packaging mamba
        # Reboot conda after updating conda to avoid subtle path bugs
        - conda deactivate
        - conda activate
        # Useful for debugging any issues with conda
        - conda info -a
        - which python
        - cd scripts
        - python update_tags.py pcds
        - travis_wait 21 timeout 20m ./create_base_env.sh next-3.9 pcds 3.9
        - conda activate pcds-next-3.9
        - conda list
        # Set up the tests
        - python test_setup.py pcds --tag
      before_script:
        # Run windows manager
        - "herbstluftwm &"
        - sleep 1
      script:
        - ./run_all_tests.sh pcds

    - name: "Python 3.10 Next Env Unit Tests"
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p miniconda
        - source miniconda/etc/profile.d/conda.sh
        - conda activate
        - hash -r
        # Use our condarc
        - cp condarc miniconda/.condarc
        - conda config --set always_yes yes --set changeps1 no
        - conda install conda-build anaconda-client packaging mamba
        # Reboot conda after updating conda to avoid subtle path bugs
        - conda deactivate
        - conda activate
        # Useful for debugging any issues with conda
        - conda info -a
        - which python
        - cd scripts
        - python update_tags.py pcds
        - travis_wait 21 timeout 20m ./create_base_env.sh next-3.10 pcds 3.10
        - conda activate pcds-next-3.10
        - conda list
        # Set up the tests
        - python test_setup.py pcds --tag
      before_script:
        # Run windows manager
        - "herbstluftwm &"
        - sleep 1
      script:
        - ./run_all_tests.sh pcds
