language: python
dist: xenial

services:
 - xvfb

addons:
  apt:
    packages:
      - herbstluftwm
      - libxkbcommon-x11-0

matrix:
  fast_finish: true
  include:
    - name: Latest Env
      env:
      - VARIANT=yaml
      - PY_VER=3.6
    - name: py3.6 Newest Tags
      env:
      - VARIANT=tag
      - PY_VER=3.6
    - name: py3.6 Master Branch
      env:
      - VARIANT=dev
      - PY_VER=3.6
    - name: py3.7 Newest Tags
      env:
      - VARIANT=tag
      - PY_VER=3.7
    - name: py3.7 Master Branch
      env:
      - VARIANT=dev
      - PY_VER=3.7
    - name: py3.8 Newest Tags
      env:
      - VARIANT=tag
      - PY_VER=3.8
    - name: py3.8 Master Branch
      env:
      - VARIANT=dev
      - PY_VER=3.8
  allow_failures:
    - name: py3.6 Master Branch
      env:
      - VARIANT=dev
      - PY_VER=3.6
    - name: py3.7 Newest Tags
      env:
      - VARIANT=tag
      - PY_VER=3.7
    - name: py3.7 Master Branch
      env:
      - VARIANT=dev
      - PY_VER=3.7
    - name: py3.8 Newest Tags
      env:
      - VARIANT=tag
      - PY_VER=3.8
    - name: py3.8 Master Branch
      env:
      - VARIANT=dev
      - PY_VER=3.8
 
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda activate
  - hash -r
  # Use our condarc
  - cp condarc ~/.condarc
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client packaging
  - conda update -q conda conda-build
  # Reboot conda after updating conda to avoid subtle path bugs
  - conda deactivate
  - conda activate
  # Useful for debugging any issues with conda
  - conda info -a
  - |
    if [ "$VARIANT" = "yaml" ]; then
      # Create the environment from yaml
      conda env create -q -n pcds-test -f envs/pcds/env.yaml
    else
      if [ "$VARIANT" = "dev" ]; then
        # Add the dev channel to be first channel
        conda config --add channels pcds-dev
      fi
      pushd scripts
      python update_tags.py pcds
      timeout 10m ./create_base_env.sh test pcds "$PY_VER"
      popd
    fi
  - conda activate pcds-test
  # Check out the tests for all of our packages
  - |
    if [ "$VARIANT" = "dev" ]; then
      python scripts/test_setup.py pcds
    else
      python scripts/test_setup.py pcds --tag
    fi
  # Show us which test scripts exist
  - readlink -f */run_tests.py

before_script:
  # Run windows manager
  - "herbstluftwm &"
  - sleep 1

script:
  - scripts/run_all_tests.sh pcds
