name: "conda setup"
description: "download a fresh conda/mamba and prepare it for use"
runs:
  using: "composite"
  # Maybe someday default shell will be supported for actions, not just workflows
  # defaults:
  #   run:
  #     shell: bash --login -eo pipefail {0}
  steps:
    # Temporarily use python 3.10 instead of latest 3.11 due to incompatibility triangle between python, conda, and mamba. Should be fixed in mamba>1.5.1 in Oct 2023
    #- run: wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
    - run: wget -q https://repo.anaconda.com/miniconda/Miniconda3-py310_23.5.2-0-Linux-x86_64.sh -O ~/miniconda.sh
      shell: bash
    - run: bash ~/miniconda.sh -b -p ~/miniconda
      shell: bash
    - run: echo "source ~/miniconda/etc/profile.d/conda.sh" >> ~/.bash_profile
      shell: bash
    - run: echo "conda activate base" >> ~/.bash_profile
      shell: bash
    - run: echo "Conda version is $(conda --version)"
      shell: bash --login -eo pipefail {0}
    - run: cp condarc ~/.condarc
      shell: bash
    - run: conda config --set always_yes yes --set changeps1 no
      shell: bash --login -eo pipefail {0}
    - run: conda install -q mamba
      shell: bash --login -eo pipefail {0}
    - run: mamba install -q anaconda-client packaging
      shell: bash --login -eo pipefail {0}
    - run: echo "Running using python $(which python)"
      shell: bash --login -eo pipefail {0}
    - run: echo "Running using mamba $(mamba info -a)"
      shell: bash --login -eo pipefail {0}
