name: "finalize and check env"
description: "make the conda env available to future steps and show it"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "micromamba activate pcds-test" >> ~/.bash_profile
    - shell: bash
      run: mamba list | tee "$GITHUB_TEST_SUMMARY"
