name: "run tests"
description: "set up and run the full environment unit test suite"
inputs:
  use-tag:
    description: "Whether or not to test against the tag"
    required: true
    default: false
runs:
  using: "composite"
  # Maybe someday default shell will be supported for actions, not just workflows
  # defaults:
  #   run:
  #     shell: bash --login -eo pipefail {0}
  steps:
    - run: |
        cd scripts
        if ${{ inputs.use-tag }}; then
          python test_setup.py pcds --tag
        else
          python test_setup.py pcds
        fi
      shell: bash --login -eo pipefail {0}
    - run: |
        cd scripts
        ./run_all_tests.sh pcds | tee ~/test_output.log
      shell: bash --login -eo pipefail {0}
    - run: sed -n '/summary_start/{:a;n;/summary_end/b;p;ba}' ~/test_output.log >> "$GITHUB_STEP_SUMMARY"
      if: ${{ always() }}
      shell: bash
    - run: grep "Extra tests" ~/test_output.log >> "$GITHUB_STEP_SUMMARY"
      if: ${{ always() }}
      shell: bash
