name: pcds-envs Integration Testing

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  current-env-tests:
    defaults:
      run:
        shell: bash --login -eo pipefail {0}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ./.github/actions/conda_setup
    - name: create environment
      run: mamba env create -q -n pcds-test -f envs/pcds/env.yaml
    - uses: ./.github/actions/finalize_and_check_env
    - uses: ./.github/actions/run_tests
      with:
        use-tag: true
    - uses: ./.github/actions/release_notes
  next-env-tests:
    defaults:
      run:
        shell: bash --login -eo pipefail {0}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ./.github/actions/conda_setup
    - name: create environment
      run: |
        cd scripts
        ./create_incremental_env.sh test pcds master
    - uses: ./.github/actions/finalize_and_check_env
    - uses: ./.github/actions/run_tests
      with:
        use-tag: true
    - uses: ./.github/actions/release_notes
